services:
  omniroute:
    container_name: omniroute
    image: diegosouzapw/omniroute:latest
    restart: unless-stopped
    stop_grace_period: 40s

    environment:
      TZ: Europe/Berlin

    networks:
      - traefik

    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.omniroute.rule=Host(`omniroute.henahax.net`) || Host(`omniroute.henahax.de`)"
      - "traefik.http.routers.omniroute.entrypoints=websecure"
      - "traefik.http.routers.omniroute.tls=true"
      - "traefik.http.services.omniroute.loadbalancer.server.port=20128"

    volumes:
      - /container-volumes/data/omniroute:/app/data

networks:
  traefik:
    external: true
