version: "3.2"

services:
  agent:
    image: portainer/agent:latest
    volumes:
      - portainer-docker:/var/run/docker.sock
      - portainer-volumes:/var/lib/docker/volumes
    restart: unless-stopped

  portainer:
    image: portainer/portainer-ce:latest
    command: -H tcp://agent:9001 --tlsskipverify
    ports:
      - "9000:9000"
    volumes:
      - portainer-data:/data
    restart: unless-stopped
volumes:
  portainer-data:
  portainer-docker:
  portainer-volumes:
