name: henahax-gw2tool
services:
  nginx:
    container_name: henahax-gw2tools
    image: henahax/gw2tools:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    ports:
      - 8082:3000
    restart: unless-stopped
