http:
  middlewares:
    lan-only:
      ipWhiteList:
        sourceRange:
          - 192.168.0.0/16

    github:
      redirectRegex:
        regex: "^https?://github\\.henahax\\.(net|de)(/.*)?$"
        replacement: "https://github.com/henahax"
        permanent: true
