http:
  middlewares:
    lan-only:
      ipAllowList:
        sourceRange:
          - 192.168.0.0/16
          - 10.0.0.0/8
          - 172.16.0.0/12

    # subdomain renames
    gw2.net:
      redirectRegex:
        regex: "^https?://gw2tools\\.henahax\\.net(/.*)?$"
        replacement: "https://gw2.henahax.net${1}"
        permanent: true
    ## todo

    # .de to .net redirects
    gw2.de:
      redirectRegex:
        regex: "^https?://(gw2|gw2tools)\\.henahax\\.de(/.*)?$"
        replacement: "https://gw2.henahax.net${1}"
        permanent: true
    ## todo

    # subdomain to path redirects
    links:
      redirectRegex:
        regex: "^https?://(kontakt|contact|links)\\.henahax\\.(net|de)(/.*)?$"
        replacement: "https://henahax.net/contact"
        permanent: true

    magicfind:
      redirectRegex:
        regex: "^https?://(magicfind|mf)\\.henahax\\.(net|de)(/.*)?$"
        replacement: "https://gw2.henahax.net/magicfind"
        permanent: true

    reset:
      redirectRegex:
        regex: "^https?://reset\\.henahax\\.(net|de)(/.*)?$"
        replacement: "https://gw2.henahax.net/reset"
        permanent: true

    ts:
      redirectRegex:
        regex: "^https?://(ts|discord|ts3|ts6)\\.henahax\\.(net|de)(/.*)?$"
        replacement: "https://henahax.net/server"
        permanent: true
    ## todo

    # external
    discord:
      redirectRegex:
        regex: "^https?://discord\\.henahax\\.(net|de)(/.*)?$"
        replacement: "https://discord.com/invite/26Kc9mJYKT"
        permanent: true

    docker:
      redirectRegex:
        regex: "^https?://docker\\.henahax\\.(net|de)(/.*)?$"
        replacement: "https://hub.docker.com/u/henahax"
        permanent: true

    facebook:
      redirectRegex:
        regex: "^https?://facebook\\.henahax\\.(net|de)(/.*)?$"
        replacement: "https://facebook.com/henahax"
        permanent: true

    github:
      redirectRegex:
        regex: "^https?://github\\.henahax\\.(net|de)(/.*)?$"
        replacement: "https://github.com/henahax"
        permanent: true

    homelab:
      redirectRegex:
        regex: "^https?://homelab\\.henahax\\.(net|de)(/.*)?$"
        replacement: "https://github.com/henahax/homelab"
        permanent: true

    instagram:
      redirectRegex:
        regex: "^https?://instagram\\.henahax\\.(net|de)(/.*)?$"
        replacement: "https://instagram.com/henahax"
        permanent: true

    killproof:
      redirectRegex:
        regex: "^https?://(killproof|kp)\\.henahax\\.(net|de)(/.*)?$"
        replacement: "https://killproof.me/proof/z44xx"
        permanent: true

    rickroll:
      redirectRegex:
        regex: "^https?://(rickroll|info)\\.henahax\\.(net|de)(/.*)?$"
        replacement: "https://youtube.com/watch?v=dQw4w9WgXcQ"
        permanent: true

    steam:
      redirectRegex:
        regex: "^https?://steam\\.henahax\\.(net|de)(/.*)?$"
        replacement: "https://steamcommunity.com/id/henahax"
        permanent: true

    twitch:
      redirectRegex:
        regex: "^https?://twitch\\.henahax\\.(net|de)(/.*)?$"
        replacement: "https://twitch.tv/henahax"
        permanent: true

    x:
      redirectRegex:
        regex: "^https?://(x|twitter)\\.henahax\\.(net|de)(/.*)?$"
        replacement: "https://x.com/henahax"
        permanent: true
    ## todo
