http:
  routers:
    github-redirect:
      rule: "Host(`github.henahax.net`)"
      entryPoints:
        - web
        - websecure
      middlewares:
        - github-redirect
      service: noop@internal
    traefik-dashboard:
      rule: "Host(`traefik.henahax.net`)"
      entryPoints:
        - web
        - websecure
      service: api@internal
