# todo delete

http:
  routers:
    # redirects
    github-redirect:
      rule: "Host(`github.henahax.net`, `github.henahax.de`)"
      entryPoints:
        - web
        - websecure
      middlewares:
        - github
      service: noop@internal
