version: "2.1"
services:
  nginx:
    container_name: henahax-homepage
    image: henahax/homepage:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    ports:
      - 8080:4321
    restart: unless-stopped
