version: "3"
services:
  homarr:
    container_name: homarr
    image: ghcr.io/ajnart/homarr:latest
    restart: unless-stopped
    volumes:
      - /volumes/homarr/configs:/app/data/configs
      - /volumes/homarr/icons:/app/public/icons
    ports:
      - "7575:7575"
