version: "3"
services:
  homarr:
    container_name: homarr
    image: ghcr.io/ajnart/homarr:latest
    restart: unless-stopped
    volumes:
      - homarr-config:/app/data/configs
      - homarr-icons:/app/public/icons
    ports:
      - "7575:7575"
volumes:
  homarr-config:
  homarr-coicons:
