version: "2.1"
services:
  nginx:
    image: henahax/gw2-magicfind-checklist:latest
    container_name: henahax-gw2-magicfind-checklist
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    ports:
      - 8083:80
    restart: unless-stopped
