services:
  teamspeak:
    image: teamspeak:latest
    container_name: teamspeak3
    restart: unless-stopped
    environment:
      - TZ=Europe/Berlin
      - TS3SERVER_LICENSE=accept
      - TS3SERVER_QUERY_PROTOCOLS=raw,ssh,http,https
      - TS3SERVER_QUERY_HTTP_PORT=10080
      - TS3SERVER_QUERY_HTTPS_PORT=10443
    ports:
      - "9987:9987/udp" # Voice Port
      - "30033:30033/tcp" # File Transfer
      - "10011:10011/tcp" # Server Query
      - "8087:10080/tcp" # Web Query - TODO: Change
      # - "8087:10443/tcp" # Web Query - TODO: Change
    volumes:
      - teamspeak3-data:/var/ts3server/

volumes:
  teamspeak3-data:
    driver: local
    driver_opts:
      type: none
      device: /container-volumes/data/teamspeak3 # Host path on your ZFS dataset
      o: bind
