services:
  henahax-homepage:
    container_name: henahax-homepage
    image: henahax/homepage:latest
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - CACHE_TTL=${CACHE_TTL}
      - VOICE_API_URL=${VOICE_API_URL}
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.homepage.rule=Host(`henahax.net`) || Host(`www.henahax.net`) || Host(`henahax.de`) || Host(`www.henahax.de`)"
      - "traefik.http.services.homepage.loadbalancer.server.port=4321"

networks:
  traefik:
    external: true
