services:
  database:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: Henahax
      POSTGRES_PASSWORD: "password"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    ports:
      - "9432:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: mail@test.com
      PGADMIN_DEFAULT_PASSWORD: "password"
      PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION: "False"
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  postgres_data:
    driver: local
    driver_opts:
      type: none
      device: /container-volumes/data/postgres
      o: bind

  pgadmin_data:
    driver: local
    driver_opts:
      type: none
      device: /container-volumes/data/pgadmin
      o: bind
