services:
  traefik:
    image: traefik:latest
    container_name: traefik
    command:
      - "--configFile=/etc/traefik/traefik.yml"
    ports:
      - "80:80"
      - "443:443"
      - "9080:8080" # Dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik_config:/etc/traefik:ro
      - traefik_certs:/certs
    restart: unless-stopped

volumes:
  traefik_config:
    driver: local
    driver_opts:
      type: none
      device: /container-volumes/traefik/config
      o: bind

  traefik_certs:
    driver: local
    driver_opts:
      type: none
      device: /container-volumes/traefik/certs
      o: bind
