services:
  traefik:
    image: traefik:latest
    container_name: traefik
    restart: unless-stopped

    command:
      - "--configFile=/etc/traefik/traefik.yml"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"

    ports:
      - "80:80"
      - "443:443"
      - "9080:8080" # optional dashboard access

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik_config:/etc/traefik
      - traefik_data:/data

    networks:
      - traefik

volumes:
  traefik_config:
    driver: local
    driver_opts:
      type: none
      device: /container-volumes/config/traefik
      o: bind

  traefik_data:
    driver: local
    driver_opts:
      type: none
      device: /container-volumes/data/traefik
      o: bind

networks:
  traefik:
    external: true
