services:
  traefik:
    image: traefik:latest
    container_name: traefik

    command:
      - "--configFile=/etc/traefik/traefik.yml"

    ports:
      - "80:80"
      - "443:443"
      - "9080:8080" # dashboard

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

      # config (static config only)
      - traefik_config:/etc/traefik

      # data (ACME, certificates, state)
      - traefik_data:/data

    restart: unless-stopped

volumes:
  traefik_config:
    driver: local
    driver_opts:
      type: none
      device: /container-volumes/config/traefik
      o: bind

  traefik_data:
    driver: local
    driver_opts:
      type: none
      device: /container-volumes/data/traefik
      o: bind
