services:
  nextcloud:
    image: lscr.io/linuxserver/nextcloud:latest
    container_name: nextcloud
    restart: unless-stopped

    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin

    ports:
      - "9009:80"

    volumes:
      - nextcloud_config:/config
      - /mnt/files/documents/nextcloud:/data

    networks:
      - traefik
      - database

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nextcloud-local.rule=Host(`nextcloud.local`)"
      - "traefik.http.routers.nextcloud-local.entrypoints=web"
      - "traefik.http.routers.nextcloud-local.middlewares=lan-only@file"
      - "traefik.http.services.nextcloud.loadbalancer.server.port=80"

volumes:
  nextcloud_config:
    driver: local
    driver_opts:
      type: none
      device: /container-volumes/config/nextcloud
      o: bind

networks:
  traefik:
    external: true
  database:
    external: true
