services:
  nextcloud:
    container_name: nextcloud
    image: lscr.io/linuxserver/nextcloud:latest
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    ports:
      - "9009:80"
    volumes:
      - nextcloud_config:/config
      - nextcloud_data:/data
    networks:
      - traefik
      - database
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.nextcloud.rule=Host(`nextcloud.henahax.net`) || Host(`nextcloud.henahax.de`)"
      - "traefik.http.routers.nextcloud.entrypoints=websecure"
      - "traefik.http.routers.nextcloud.tls=true"
      - "traefik.http.services.nextcloud.loadbalancer.server.port=80"

volumes:
  nextcloud_config:
    driver: local
    driver_opts:
      type: none
      device: /container-volumes/config/nextcloud
      o: bind
  nextcloud_data:
    driver: local
    driver_opts:
      type: none
      device: /mnt/files/cloud
      o: bind

networks:
  traefik:
    external: true
  database:
    external: true
