version: "2.1"
services:
  foldingathome:
    container_name: foldingathome
    image: lscr.io/linuxserver/foldingathome:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes:
      - foldingathome-config:/config
    ports:
      - 7396:7396
      - 36330:36330 #optional
    restart: unless-stopped

volumes:
  foldingathome-config:
