services:
  homarr:
    container_name: homarr
    image: ghcr.io/homarr-labs/homarr:latest
    restart: unless-stopped

    environment:
      - SECRET_ENCRYPTION_KEY=8483eeef15e492f2ebc4373e01522679fd5d8f5b0df73bd145c870efee43f736

    volumes:
      # optional Docker integration
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - homarr_data:/appdata

    networks:
      - traefik

    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.homarr.rule=Host(`homarr.henahax.net`) || Host(`homarr.henahax.de`) || Host(`dashboard.henahax.net`) || Host(`dashboard.henahax.de`)"
      - "traefik.http.routers.homarr.entrypoints=websecure"
      - "traefik.http.routers.homarr.tls=true"
      - "traefik.http.services.homarr.loadbalancer.server.port=7575"

volumes:
  homarr_data:
    driver: local
    driver_opts:
      type: none
      device: /container-volumes/data/homarr
      o: bind

networks:
  traefik:
    external: true
