version: "2.1"
services:
  nginx:
    container_name: henahax-treasurehunt
    image: henahax/treasurehunt:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    ports:
      - 8085:3000
    restart: unless-stopped
